// 전체 UI 한국어 텍스트 상수 — 존댓말, 쉬운 표현 사용
export const strings = {
  appName: 'SilverRide',
  loading: '잠시만 기다려 주세요...',
  error: '죄송합니다, 잠시 후 다시 시도해 주세요.',
  confirm: '확인',
  cancel: '취소',
  back: '뒤로 가기',
  close: '닫기',
  home: {
    title: '어디로 가실까요?',
    callTaxi: '택시 부르기',
    goHome: '집으로 가기',
    goHospital: '병원 가기',
    favorites: '즐겨찾는 곳',
    sos: 'SOS 긴급호출',
    greeting: '안녕하세요! 오늘도 좋은 하루 되세요.',
  },
  destination: {
    title: '목적지를 선택해 주세요',
    inputPlaceholder: '목적지를 입력해 주세요',
    voiceInput: '말로 알려주세요',
    recentPlaces: '최근 방문한 곳',
    favorites: '즐겨찾는 곳',
    searchResult: '검색 결과',
    noResult: '검색 결과가 없습니다.',
  },
  rideConfirm: {
    title: '택시를 부를까요?',
    estimatedFare: '예상 요금',
    estimatedTime: '예상 시간',
    callButton: '택시 부르기',
    won: '원',
    minutes: '분',
    fareNotice: '실제 요금은 다를 수 있습니다.',
  },
  waiting: {
    title: '택시를 찾고 있어요',
    searching: '기사님을 배정하고 있습니다...',
    driverFound: '기사님이 오고 있어요!',
    estimatedArrival: '도착 예정',
    driverInfo: '기사 정보',
    cancelButton: '취소하기',
    carNumber: '차량 번호',
  },
  riding: {
    title: '안전하게 이동 중이에요',
    destination: '목적지',
    estimatedArrival: '도착 예정',
    sos: 'SOS 긴급호출',
  },
  paymentComplete: {
    title: '도착했습니다!',
    fare: '결제 금액',
    rating: '기사님은 어떠셨나요?',
    ratingGood: '좋았어요',
    ratingBad: '불편했어요',
    done: '완료',
    familyNotice: '가족에게 도착 알림을 보냈습니다.',
  },
  emergency: {
    title: 'SOS 긴급호출',
    calling: '긴급 연락 중...',
    callingFamily: '보호자에게 연락 중입니다.',
    callingPolice: '경찰에 신고 중입니다.',
    cancel: '취소',
    message: '도움이 필요하세요? 잠시만 기다려 주세요.',
  },
  auth: {
    title: '휴대폰 번호를 입력해 주세요',
    phonePlaceholder: '010-0000-0000',
    sendCode: '인증번호 받기',
    codePlaceholder: '인증번호 6자리',
    verifyCode: '인증 확인',
    resendCode: '인증번호 다시 받기',
    success: '인증이 완료됐습니다.',
  },
  myPage: {
    title: '내 정보',
    favorites: '즐겨찾기 관리',
    familyLink: '보호자 연동',
    settings: '설정',
    slowMode: '느린 말하기 모드',
    voiceOnlyMode: '음성 전용 모드',
    logout: '로그아웃',
  },
  familyLink: {
    title: '보호자 연동',
    description: '보호자 휴대폰 번호를 입력해 주세요.',
    phonePlaceholder: '보호자 휴대폰 번호',
    linkButton: '연동하기',
    linked: '연동된 보호자',
    unlink: '연동 해제',
  },
  tts: {
    homeGreeting: '어디로 가실까요?',
    taxiCalling: '택시를 부르고 있습니다. 잠시만 기다려 주세요.',
    driverFound: '기사님이 배정됐습니다. 곧 도착합니다.',
    arrived: '목적지에 도착했습니다. 안전하게 내려 주세요.',
    sosActivated: '긴급 신호를 보내고 있습니다. 보호자에게 연락 중입니다.',
    umbrellaReminder: '오늘 비가 올 예정입니다. 우산을 챙겨 주세요.',
    medicationReminder: '병원 다녀오면 약 드시는 거 잊지 마세요.',
    familyArrivalNotice: '어르신이 안전하게 도착했습니다.',
  },
  weather: {
    rainWarning: '비가 올 예정입니다. 우산을 챙겨 주세요.',
  },
  onboarding: {
    slide1Title: '어르신을 위한 택시',
    slide1Desc: '큰 글씨, 쉬운 조작으로\n편리하게 이용하세요.',
    slide2Title: '음성으로 간편하게',
    slide2Desc: '말 한마디면 택시가 와요.\n버튼 누를 필요도 없어요.',
    slide3Title: '가족과 함께 안심하게',
    slide3Desc: '도착하면 가족에게\n자동으로 알려드려요.',
    start: '시작하기',
    skip: '건너뛰기',
    next: '다음',
  },
};
